/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day2;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;

public class App {
    private static final int MAX_RED = 12;
    private static final int MAX_GREEN = 13;
    private static final int MAX_BLUE = 14;

    public static void main(String[] args) {
        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        InputStream is = classloader.getResourceAsStream("input");
        InputStreamReader streamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
        BufferedReader reader = new BufferedReader(streamReader);
        int result = 0;
        try {
            result = run(reader);
        } catch(Exception e) {
            System.err.println(e.toString());
            return;
        }
        System.out.println("Result: " + result);
    }
    public static int run(BufferedReader reader) throws Exception {
        int result = 0;
        ArrayList<Game> games = new ArrayList<Game>();
        for (String line; (line = reader.readLine()) != null;) {
            games.add(Parser.getGame(line));
        }
        for (Game game : games) {
            if (game.isPossible(MAX_RED, MAX_GREEN, MAX_BLUE)){
                result += game.getID();
            }
        }
        return result;
    }
}
