/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day3;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        InputStream is = classloader.getResourceAsStream("input");
        InputStreamReader streamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
        BufferedReader reader = new BufferedReader(streamReader);
        int result = 0;
        try {
            result = run(reader);
        } catch(Exception e) {
            System.err.println(e.toString());
            return;
        }
        System.out.println("Result: " + result);
    }
    public static int run(BufferedReader reader) throws Exception{
        ArrayList<String> lines = new ArrayList<String>();
        for(String line; (line = reader.readLine()) != null;){
            lines.add(line);
        }
        State state = new State(lines);
        return state.scan();
    }
}
