/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day4;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        InputStream is = classloader.getResourceAsStream("input");
        InputStreamReader streamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
        BufferedReader reader = new BufferedReader(streamReader);
        PointCalculator.init_ticket_count();
        try {
        for(String line; (line = reader.readLine()) != null;){
            PointCalculator.calculatePoints(line);
        }
        } catch(Exception e) {
            System.err.println(e.toString());
            return;
        }
        int total = 0;
        for (int value : PointCalculator.ticket_count.values()){
            total += value;
        }
        System.out.println("Result: " + total);
    }
}
