/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package day4;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        InputStream is = classloader.getResourceAsStream("input");
        InputStreamReader streamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
        BufferedReader reader = new BufferedReader(streamReader);
        int result = 0;
        try {
        for(String line; (line = reader.readLine()) != null;){
            result += PointCalculator.calculatePoints(line);
        }
        } catch(Exception e) {
            System.err.println(e.toString());
            return;
        }
        System.out.println("Result: " + result);
    }
}
